version: "3.8"

services:
  # API GATEWAY - TRAEFIK
  traefik:
    image: traefik:v3.5
    container_name: traefik-pedestrian
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - pedestrian-net

  # LOGIN SERVICE
  login-service:
    build: ./login_service
    container_name: login-service
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - pedestrian-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.login.rule=PathPrefix(`/login`)"
      - "traefik.http.routers.login.entrypoints=web"
      - "traefik.http.middlewares.login-strip.stripprefix.prefixes=/login"
      - "traefik.http.routers.login.middlewares=login-strip"
      - "traefik.http.services.login.loadbalancer.server.port=8080"
    environment:
      - SPRING_METRICS_EXPORT_PROMETHEUS_ENABLED=true # Habilitar métricas para Prometheus
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: logindb
    ports:
      - "27017:27017"
    networks:
      - pedestrian-net
  # EMPLOYEE SERVICE
  employee-service:
    build: ./employee_service
    container_name: employee-service
    depends_on:
      - login-service
      - rabbitmq
    networks:
      - pedestrian-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.employee.rule=PathPrefix(`/employee`)"
      - "traefik.http.routers.employee.entrypoints=web"
      - "traefik.http.services.employee.loadbalancer.server.port=8080"
    environment:
      - SPRING_METRICS_EXPORT_PROMETHEUS_ENABLED=true # Habilitar métricas para Prometheus

  # ACCESS SERVICE
  access-service:
    build: ./access_service
    container_name: access-service
    depends_on:
      - employee-service
      - rabbitmq
    networks:
      - pedestrian-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.access.rule=PathPrefix(`/access`)"
      - "traefik.http.routers.access.entrypoints=web"
      - "traefik.http.services.access.loadbalancer.server.port=8080"
    environment:
      - SPRING_METRICS_EXPORT_PROMETHEUS_ENABLED=true # Habilitar métricas para Prometheus

  # ALERT SERVICE
  alert-service:
    build: ./alert_service
    container_name: alert-service
    depends_on:
      - rabbitmq
    networks:
      - pedestrian-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alert.rule=PathPrefix(`/alert`)"
      - "traefik.http.routers.alert.entrypoints=web"
      - "traefik.http.services.alert.loadbalancer.server.port=8080"
    environment:
      - SPRING_METRICS_EXPORT_PROMETHEUS_ENABLED=true # Habilitar métricas para Prometheus

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-saga
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pedestrian-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.39.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # El archivo de configuración de Prometheus
    ports:
      - "9090:9090" # Puerto de Prometheus
    networks:
      - pedestrian-net

  # GRAFANA
  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Contraseña predeterminada para el administrador
    ports:
      - "3000:3000" # Puerto de Grafana
    depends_on:
      - prometheus
    networks:
      - pedestrian-net

networks:
  pedestrian-net:
    driver: bridge
